/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBarBackgroundImage: typeof import('./components/AppBarBackgroundImage.vue')['default']
    AppFileInput: typeof import('./components/AppFileInput.vue')['default']
    AppFileInspector: typeof import('./components/AppFileInspector.vue')['default']
    AppFileLog: typeof import('./components/AppFileLog.vue')['default']
    AppThemeToggle: typeof import('./components/AppThemeToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
